// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTEi-5I-YeGXrxGtPp6SM2ehDskzPLMqI',
    appId: '1:472182699665:web:ae57014a49545cb3f5b130',
    messagingSenderId: '472182699665',
    projectId: 'ai-book-suggest',
    authDomain: 'ai-book-suggest.firebaseapp.com',
    storageBucket: 'ai-book-suggest.firebasestorage.app',
    measurementId: 'G-1PPP9VHGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9XZNYE16B82_GUU0CnEJhBl55ast3tOY',
    appId: '1:472182699665:android:68fbb862ab24994bf5b130',
    messagingSenderId: '472182699665',
    projectId: 'ai-book-suggest',
    storageBucket: 'ai-book-suggest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1oMc3k4tk-N7MPrNlPVmGTjEpqPO45A',
    appId: '1:472182699665:ios:536bf9ce1d0facd7f5b130',
    messagingSenderId: '472182699665',
    projectId: 'ai-book-suggest',
    storageBucket: 'ai-book-suggest.firebasestorage.app',
    iosBundleId: 'com.example.aiBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1oMc3k4tk-N7MPrNlPVmGTjEpqPO45A',
    appId: '1:472182699665:ios:536bf9ce1d0facd7f5b130',
    messagingSenderId: '472182699665',
    projectId: 'ai-book-suggest',
    storageBucket: 'ai-book-suggest.firebasestorage.app',
    iosBundleId: 'com.example.aiBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTEi-5I-YeGXrxGtPp6SM2ehDskzPLMqI',
    appId: '1:472182699665:web:acfa7a71058d0f6df5b130',
    messagingSenderId: '472182699665',
    projectId: 'ai-book-suggest',
    authDomain: 'ai-book-suggest.firebaseapp.com',
    storageBucket: 'ai-book-suggest.firebasestorage.app',
    measurementId: 'G-YCMNEBE4H4',
  );
}
